### ISSUE TITLE
Update required

### ISSUE THREAD

**Issue by vanja-san** [Catgrills/Sigma#5]
There is a new collapsed left panel.
And if you can, do a search in the center, please! 🥺
Or is it because of the font I have everything crooked?

![изображение](https://user-images.githubusercontent.com/7201687/60798680-d231e980-a19b-11e9-9d76-b34f23f27d9a.png)

**Comment by Catgrills** [comment]
Updated the script, it should be alright now.

**Comment by vanja-san** [comment]
Thanks!
